language: ruby
cache: bundler # caching to speed up dependency installation
rvm:
- 2.5
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
- bundle exec jekyll build
- echo "Finished build."
jobs:
  include:
    - stage: build
      script: script/build
    - stage: testlinks
      script: REPLACE-ME-WITH-HTML-PROOFER-SCRIPT
